### ISSUE TITLE
关于rtc

### ISSUE THREAD

**Issue by billionfish** [mingjkl/nRF-Connect-SDK-Demo#1]
网上老的nrf52 SDK有很多rtc的demo，基于NCS的demo几乎没有，而这个仓库rtc应该是nrfx的api写法。相比较老的sdk多了中断引入和nrfx_rtc_cc_set。
1是想问ncs有没有不用compare的定时实现？比如类似nrf52直接用tick事件？有demo吗，
2是授人以渔，请问这些rtc的demo的来源是哪里？
困扰我很长时间了，感谢！

**Comment by billionfish** [comment]
> 网上老的nrf52 SDK有很多rtc的demo，基于NCS的demo几乎没有，而这个仓库rtc应该是nrfx的api写法。相比较老的sdk多了中断引入和nrfx_rtc_cc_set。 1是想问ncs有没有不用compare的定时实现？比如类似nrf52直接用tick事件？有demo吗， 2是授人以渔，请问这些rtc的demo的来源是哪里？ 困扰我很长时间了，感谢！

实现了tick事件，必须加IRQ_DIRECT_CONNECT这一行代码才行。默认中断是关闭的。
问题2没有解决

**Comment by mingjkl** [comment]
参考SDK中的demo“\modules\hal\nordic\nrfx\samples\src”和“\nrf\samples”的内容写的；
rtc那个deme应该是我参考timer的demo实现的；
github上的消息看的比较少，欢迎关注gitee.com/mingkjl/nordic-connect-sdk-demo
